### ISSUE TITLE
请问如何修改gptacademic的config.py? 修改好config_private.py后依然提示未填入apikey

### ISSUE THREAD

**Issue by GitYohoo** [elphen-wang/FreeAI#1]

**Comment by elphen-wang** [comment]
> 

按config_private.py原样填回去。

**Comment by GitYohoo** [comment]
Traceback (most recent call last):
  File "D:\Desktop\gptacademic\gpt_academic\toolbox.py", line 671, in read_single_conf_with_lru_cache
    default_ref = getattr(importlib.import_module('config'), arg)   # 读取默认值作为数据类型转换的参考
AttributeError: module 'config' has no attribute 'API_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Desktop\gptacademic\gpt_academic\toolbox.py", line 676, in read_single_conf_with_lru_cache
    r = getattr(importlib.import_module('config_private'), arg)
AttributeError: module 'config_private' has no attribute 'API_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Desktop\gptacademic\gpt_academic\main.py", line 236, in <module>
    main()
  File "D:\Desktop\gptacademic\gpt_academic\main.py", line 57, in main
    cookies = gr.State(load_chat_cookies())
  File "D:\Desktop\gptacademic\gpt_academic\toolbox.py", line 531, in load_chat_cookies
    API_KEY, LLM_MODEL, AZURE_API_KEY = get_conf('API_KEY', 'LLM_MODEL', 'AZURE_API_KEY')
  File "D:\Desktop\gptacademic\gpt_academic\toolbox.py", line 702, in get_conf
    r = read_single_conf_with_lru_cache(arg)
  File "D:\Desktop\gptacademic\gpt_academic\toolbox.py", line 679, in read_single_conf_with_lru_cache
    r = getattr(importlib.import_module('config'), arg)
AttributeError: module 'config' has no attribute 'API_KEY'

**Comment by elphen-wang** [comment]
> Traceback (most recent call last): File "D:\Desktop\gptacademic\gpt_academic\toolbox.py", line 671, in read_single_conf_with_lru_cache default_ref = getattr(importlib.import_module('config'), arg) # 读取默认值作为数据类型转换的参考 AttributeError: module 'config' has no attribute 'API_KEY'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "D:\Desktop\gptacademic\gpt_academic\toolbox.py", line 676, in read_single_conf_with_lru_cache r = getattr(importlib.import_module('config_private'), arg) AttributeError: module 'config_private' has no attribute 'API_KEY'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "D:\Desktop\gptacademic\gpt_academic\main.py", line 236, in main() File "D:\Desktop\gptacademic\gpt_academic\main.py", line 57, in main cookies = gr.State(load_chat_cookies()) File "D:\Desktop\gptacademic\gpt_academic\toolbox.py", line 531, in load_chat_cookies API_KEY, LLM_MODEL, AZURE_API_KEY = get_conf('API_KEY', 'LLM_MODEL', 'AZURE_API_KEY') File "D:\Desktop\gptacademic\gpt_academic\toolbox.py", line 702, in get_conf r = read_single_conf_with_lru_cache(arg) File "D:\Desktop\gptacademic\gpt_academic\toolbox.py", line 679, in read_single_conf_with_lru_cache r = getattr(importlib.import_module('config'), arg) AttributeError: module 'config' has no attribute 'API_KEY'

。。。log已经告诉你报错点在哪了

**Comment by GitYohoo** [comment]
我知道 就是config.py中找不到API_KEY字段嘛，不知道怎么改🤣  gptacademic好像更新了 求大佬跟进

**Comment by elphen-wang** [comment]
> 我知道 就是config.py中找不到API_KEY字段嘛，不知道怎么改🤣 gptacademic好像更新了 求大佬跟进
那你重新下原本的config.py，重新填就好。config和config_private内容可以一模一样。
(https://github.com/binary-husky/gpt_academic/blob/master/config.py)

**Comment by hc9903** [comment]
好像需要把API_KEYAPI_KEY修改为API_KEY
下面是我修改后打包的镜像，可以直接用Share Token池
docker run -d -v /root/arxiv_cache:/root/arxiv_cache --env AUTHENTICATION='[("test", "test")]'  --net=host --restart=always --name gpt-academic-freepool superzer000/gpt-academic-nolocal-latex:freepool
