### ISSUE TITLE
需要更新

### ISSUE THREAD

**Issue by wingwwwc** [elphen-wang/FreeAI#6]
不知道是不是因为原项目修改了，config里面多了几个变量，然后”API_KEY“变量名也和本项目中config_private中的不一样。直接完全用config_private覆盖config会提示缺失一些变量设置。
我只把原config中的step1 替换成了本项目中config_private的内容。然后在config_private和config文件中修改API_KEYAPI_KEY 参数名成API_KEY，并且API_KEY的值改成"pk-this-is-a-real-free-pool-token-for-everyone".
然后就能使用了。

我把替换内容单独放在下面，直接按上面说的在config和config_private中用下面这条覆盖了就能用了。

`API_KEY = "pk-this-is-a-real-free-pool-token-for-everyone"    # 可同时填写多个API-KEY，用英文逗号分割，例如API_KEY = "sk-openaikey1,sk-openaikey2,fkxxxx-api2dkey3,azure-apikey4"`

**Comment by wingwwwc** [comment]
写完这个当天晚上又不能用了，不知道是不是原项目更新了的原因。
1.使用上一个版本的gpt_academic，新版本放进去会有toolbox的报错，老版本就只会api报错，因此我先用旧版本改改看。
2.在旧版本中使用pk-this-is-a-real-free-pool-token-for-everyone提示有法律风险不让用，尝试使用share_token的方法。
3."get_freeai_api.py"中Auth0()的参数名改变了，那句话应该替换成auth = Auth0(email_address=username, password=password).

改完之后运行get_freeai_api任然报错
`failed to do request: Get "https://chat.openai.com/api/auth/csrf": dial tcp 104.23.125.189:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.` 
不知道是服务的问题还是网络的问题

**Comment by elphen-wang** [comment]
> 写完这个当天晚上又不能用了，不知道是不是原项目更新了的原因。 1.使用上一个版本的gpt_academic，新版本放进去会有toolbox的报错，老版本就只会api报错，因此我先用旧版本改改看。 2.在旧版本中使用pk-this-is-a-real-free-pool-token-for-everyone提示有法律风险不让用，尝试使用share_token的方法。 3."get_freeai_api.py"中Auth0()的参数名改变了，那句话应该替换成auth = Auth0(email_address=username, password=password).改完之后运行get_freeai_api任然报错, 无法正常获取share_token（应该是我装的OpenAIAuth的版本的问题？我直接pip装的）。 4.直接去Pandora 项目手动获取一下access token 然后通过访问https://ai.fakeopen.com/token 获取share_token粘贴到config和config_private 的 API_KEY =“xxxx”里面即可使用了。（不用把方法二注释打开）
> 
> 总结: 1.使用上一个版本的gpt_academic（昨晚“gpt_academic”的"批量Markdown翻译.py"和"toolbox.py"更新了一点点内容），新版本放进去会有他们的报错，老版本就只会api报错。 2.api只是公共的那两个不让用了，直接去Pandora 项目手动获取一下access token 然后通过访问 https://ai.fakeopen.com/token 获取share_token，粘贴到config和config_priviate 的 API_KEY =“xxxx”里面即可暂时使用14天了。

我也做了新的更新，想自己这边努力一劳永逸解决pandora Access token生命周期的问题，看我新版内容。
